import { Router } from 'express';
import { z } from 'zod';
import { query } from '../db';
import { requireAuth, getFreshRole, getUserProjectIds, JwtPayload } from '../middleware/auth';
import { FeedbackSchema, UpdateFeedbackStatusSchema, UpdateFeedbackTriageSchema } from '../schemas/feedback';
import { getProjectPlanStatus, notifyLimitReached, incrementUsageCount } from '../helpers/plan';
import { Feedback, Project } from '../schemas/tables';

const router = Router();

// Submit feedback (public — widget calls this)
router.post('/', async (req, res) => {
    try {
        const event = FeedbackSchema.parse(req.body);

        // Check project exists — don't auto-create
        const projectCheck = await query<Pick<Project, 'id'>>('SELECT id FROM projects WHERE id = $1', [event.project_id]);
        if (projectCheck.rows.length === 0) {
            res.status(404).json({
                success: false,
                error: 'Project not found. Please create the project in the admin dashboard first.',
            });
            return;
        }

        // Check plan usage limit before inserting
        const planStatus = await getProjectPlanStatus(event.project_id);
        if (!planStatus.can_submit) {
            notifyLimitReached(event.project_id, planStatus.tickets_used, planStatus.tickets_limit);

            res.status(429).json({
                success: false,
                error: 'limit_reached',
                message: planStatus.message,
                tickets_used: planStatus.tickets_used,
                tickets_limit: planStatus.tickets_limit,
            });
            return;
        }

        const text = `
      INSERT INTO feedback (
        project_id, type, timestamp, event_id, title, description, category, severity, impact, email,
        url, route, screen_id, page_name,
        context, metadata, screenshots, highlighted_element,
        user_id, tenant_id, role, bernstein_run_id
      ) VALUES (
        $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22
      ) RETURNING id
    `;

        const ctx = event.context as any;
        const values = [
            event.project_id,
            event.type,
            event.timestamp || new Date().toISOString(),
            event.event_id ?? null,
            event.title,
            event.description ?? null,
            event.category ?? null,
            event.severity ?? null,
            event.impact ?? null,
            event.email ?? null,
            ctx?.url ?? null,
            ctx?.route ?? null,
            ctx?.screenId ?? null,
            ctx?.pageName ?? null,
            event.context ? JSON.stringify(event.context) : null,
            event.metadata ? JSON.stringify(event.metadata) : null,
            JSON.stringify(event.screenshots || []),
            event.highlighted_element ? JSON.stringify(event.highlighted_element) : null,
            event.user_id ?? null,
            event.tenant_id ?? null,
            event.role ?? null,
            event.bernstein_run_id ?? null
        ];

        const result = await query<Pick<Feedback, 'id'>>(text, values);

        await incrementUsageCount(event.project_id);

        // NOTE: Notifications for this feedback are generated by the
        // Postgres trigger `on_new_feedback` which fans out to project
        // members + global admins. Do NOT insert notifications here or
        // every event will produce duplicate rows (once from this handler,
        // once from the trigger). The trigger is the single source of truth.

        res.status(201).json({
            success: true,
            id: result.rows[0].id
        });

    } catch (error) {
        if (error instanceof z.ZodError) {
            console.error('Validation Error:', error.errors);
            res.status(400).json({ success: false, error: 'Validation failed', details: error.errors });
        } else {
            const msg = error instanceof Error ? error.message : String(error);
            console.error('Server Error:', msg, error);
            res.status(500).json({ success: false, error: msg });
        }
    }
});

// List feedback (with filters) — scoped by role
router.get('/', requireAuth, async (req, res) => {
    try {
        const user = (req as any).user as JwtPayload;
        const { project_id, type, status, severity, priority, limit = '50', offset = '0' } = req.query;

        let sql = 'SELECT id, project_id, type, title, description, category, severity, impact, email, screen_id, page_name, user_id, tenant_id, screenshots, status, resolved_at, labels, priority, created_at FROM feedback';
        const conditions: string[] = [];
        const values: any[] = [];
        let paramIndex = 1;

        const feedbackRole = await getFreshRole(user.user_id, user.role);
        if (feedbackRole !== 'admin') {
            const projectIds = await getUserProjectIds(user.user_id);
            if (projectIds.length === 0) {
                res.json({ success: true, data: [], total: 0 });
                return;
            }
            conditions.push(`project_id = ANY($${paramIndex++})`);
            values.push(projectIds);
        }

        if (project_id) { conditions.push(`project_id = $${paramIndex++}`); values.push(project_id); }
        if (type) { conditions.push(`type = $${paramIndex++}`); values.push(type); }
        if (status) { conditions.push(`status = $${paramIndex++}`); values.push(status); }
        if (severity) { conditions.push(`severity = $${paramIndex++}`); values.push(severity); }
        if (priority) { conditions.push(`priority = $${paramIndex++}`); values.push(priority); }

        if (conditions.length > 0) sql += ' WHERE ' + conditions.join(' AND ');
        sql += ` ORDER BY created_at DESC LIMIT $${paramIndex++} OFFSET $${paramIndex++}`;
        values.push(parseInt(limit as string), parseInt(offset as string));

        const result = await query(sql, values);
        res.json({ success: true, data: result.rows, total: result.rowCount });
    } catch (error) {
        const msg = error instanceof Error ? error.message : String(error);
        console.error('List Error:', msg);
        res.status(500).json({ success: false, error: msg });
    }
});

// Get stats/analytics (MUST be before :id route) — scoped by role
router.get('/stats/summary', requireAuth, async (req, res) => {
    try {
        const user = (req as any).user as JwtPayload;
        const { project_id } = req.query;

        const conditions: string[] = [];
        const params: any[] = [];
        let paramIndex = 1;

        const statsRole = await getFreshRole(user.user_id, user.role);
        if (statsRole !== 'admin') {
            const projectIds = await getUserProjectIds(user.user_id);
            if (projectIds.length === 0) {
                res.json({ success: true, data: { total: 0, by_type: {}, by_severity: {} } });
                return;
            }
            conditions.push(`project_id = ANY($${paramIndex++})`);
            params.push(projectIds);
        }

        if (project_id) {
            conditions.push(`project_id = $${paramIndex++}`);
            params.push(project_id);
        }

        const where = conditions.length > 0 ? 'WHERE ' + conditions.join(' AND ') : '';
        const sevWhere = conditions.length > 0
            ? where + ' AND severity IS NOT NULL'
            : 'WHERE severity IS NOT NULL';

        const total = await query<{ count: string }>(`SELECT COUNT(*) as count FROM feedback ${where}`, params);
        const byType = await query<{ type: string; count: string }>(`SELECT type, COUNT(*) as count FROM feedback ${where} GROUP BY type`, params);
        const bySeverity = await query<{ severity: string; count: string }>(`SELECT severity, COUNT(*) as count FROM feedback ${sevWhere} GROUP BY severity`, params);

        res.json({
            success: true,
            data: {
                total: parseInt(total.rows[0]?.count || '0'),
                by_type: Object.fromEntries(byType.rows.map((r) => [r.type, parseInt(r.count)])),
                by_severity: Object.fromEntries(bySeverity.rows.map((r) => [r.severity, parseInt(r.count)])),
            }
        });
    } catch (error) {
        const msg = error instanceof Error ? error.message : String(error);
        res.status(500).json({ success: false, error: msg });
    }
});

// P4: Feedback loop health metrics for the admin dashboard card.
// Delegates to the feedback_loop_health SQL function so the arithmetic
// lives in one place (and can be reused by BI tools). Computes per
// ?project_id=X, or globally if omitted.
router.get('/stats/loop-health', requireAuth, async (req, res) => {
    try {
        const user = (req as any).user as JwtPayload;
        const projectId = typeof req.query.project_id === 'string' ? req.query.project_id : null;

        // Non-admins can only query their own projects.
        const role = await getFreshRole(user.user_id, user.role);
        if (role !== 'admin') {
            if (!projectId) {
                res.status(400).json({ success: false, error: 'project_id is required for non-admin users' });
                return;
            }
            const projectIds = await getUserProjectIds(user.user_id);
            if (!projectIds.includes(projectId)) {
                res.status(403).json({ success: false, error: 'Forbidden' });
                return;
            }
        }

        const result = await query<{
            avg_resolution_hours: string | null;
            pct_closed_14d: string | null;
            return_rate: string | null;
            total_30d: string;
            resolved_30d: string;
            unique_submitters_90d: string;
            returning_submitters_90d: string;
        }>(`SELECT * FROM feedback_loop_health($1)`, [projectId]);

        const row = result.rows[0] || {} as any;
        const avgHours = row.avg_resolution_hours != null ? parseFloat(row.avg_resolution_hours) : null;
        const pctClosed = row.pct_closed_14d != null ? parseFloat(row.pct_closed_14d) : null;
        const returnRate = row.return_rate != null ? parseFloat(row.return_rate) : null;

        // Traffic-light thresholds (the spec calls for green/amber/red).
        const statusFor = (
            value: number | null,
            good: number,
            warn: number,
            higherIsBetter: boolean,
        ): 'green' | 'amber' | 'red' | 'unknown' => {
            if (value == null) return 'unknown';
            if (higherIsBetter) {
                if (value >= good) return 'green';
                if (value >= warn) return 'amber';
                return 'red';
            } else {
                if (value <= good) return 'green';
                if (value <= warn) return 'amber';
                return 'red';
            }
        };

        const avgHoursStatus = statusFor(avgHours, 48, 168, false); // green ≤ 48h, amber ≤ 7d, red > 7d
        const pctClosedStatus = statusFor(pctClosed, 80, 50, true); // green ≥ 80%, amber ≥ 50%
        const returnRateStatus = statusFor(returnRate, 40, 15, true); // green ≥ 40%, amber ≥ 15%

        // Overall is the worst of the three (red > amber > green).
        const rank = (s: string) => ({ unknown: -1, green: 0, amber: 1, red: 2 }[s] ?? -1);
        const overall = [avgHoursStatus, pctClosedStatus, returnRateStatus].reduce((worst, s) =>
            rank(s) > rank(worst) ? s : worst, 'green' as const);

        res.json({
            success: true,
            data: {
                project_id: projectId,
                metrics: {
                    avg_resolution_hours: avgHours,
                    pct_closed_14d: pctClosed,
                    return_rate: returnRate,
                },
                status: {
                    avg_resolution: avgHoursStatus,
                    pct_closed_14d: pctClosedStatus,
                    return_rate: returnRateStatus,
                    overall,
                },
                counts: {
                    total_30d: parseInt(row.total_30d || '0'),
                    resolved_30d: parseInt(row.resolved_30d || '0'),
                    unique_submitters_90d: parseInt(row.unique_submitters_90d || '0'),
                    returning_submitters_90d: parseInt(row.returning_submitters_90d || '0'),
                },
            },
        });
    } catch (error) {
        const msg = error instanceof Error ? error.message : String(error);
        res.status(500).json({ success: false, error: msg });
    }
});

// Get single feedback with full context — scoped by role
router.get('/:id', requireAuth, async (req, res) => {
    try {
        const user = (req as any).user as JwtPayload;
        const result = await query<Feedback>('SELECT * FROM feedback WHERE id = $1', [req.params.id]);
        if (result.rows.length === 0) {
            res.status(404).json({ success: false, error: 'Not found' });
            return;
        }

        const detailRole = await getFreshRole(user.user_id, user.role);
        if (detailRole !== 'admin') {
            const projectIds = await getUserProjectIds(user.user_id);
            if (!projectIds.includes(result.rows[0].project_id)) {
                res.status(403).json({ success: false, error: 'Access denied' });
                return;
            }
        }

        res.json({ success: true, data: result.rows[0] });
    } catch (error) {
        const msg = error instanceof Error ? error.message : String(error);
        res.status(500).json({ success: false, error: msg });
    }
});

// Update feedback status (resolve, close, etc.)
router.patch('/:id/status', requireAuth, async (req, res) => {
    try {
        const { status, resolution_note } = UpdateFeedbackStatusSchema.parse(req.body);

        const user = (req as any).user as JwtPayload;

        const sets: string[] = [`status = $1`];
        const values: any[] = [status];
        let i = 2;

        if (status === 'resolved' || status === 'closed') {
            sets.push(`resolved_at = $${i++}`);
            values.push(new Date().toISOString());
            sets.push(`resolved_by = $${i++}`);
            values.push(user.email);
        } else {
            sets.push(`resolved_at = $${i++}`);
            values.push(null);
            sets.push(`resolved_by = $${i++}`);
            values.push(null);
        }

        if (resolution_note !== undefined) {
            sets.push(`resolution_note = $${i++}`);
            values.push(resolution_note);
        }

        values.push(req.params.id);
        const result = await query<Pick<Feedback, 'id' | 'project_id' | 'title' | 'status' | 'user_id' | 'resolved_at' | 'resolved_by'>>(
            `UPDATE feedback SET ${sets.join(', ')} WHERE id = $${i} RETURNING id, project_id, title, status, user_id, resolved_at, resolved_by`,
            values
        );

        if (result.rows.length === 0) {
            res.status(404).json({ success: false, error: 'Feedback not found' });
            return;
        }

        const feedback = result.rows[0];

        // NOTE: The resolve notification is generated by the Postgres
        // trigger `on_feedback_resolved` (and the email by
        // `on_feedback_resolved_email`). Do NOT insert notifications here
        // or every resolve will produce duplicate rows — which is exactly
        // what happened in the earlier version of this handler.

        res.json({ success: true, data: feedback });
    } catch (error) {
        if (error instanceof z.ZodError) {
            res.status(400).json({ success: false, error: 'Validation failed', details: error.errors });
        } else {
            const msg = error instanceof Error ? error.message : String(error);
            res.status(500).json({ success: false, error: msg });
        }
    }
});

// Update feedback triage fields (P3) — labels and/or priority.
// Send any subset; fields not included in the body are untouched.
// Examples:
//   PATCH /api/feedback/<id>/triage  { "priority": "high" }
//   PATCH /api/feedback/<id>/triage  { "labels": ["backend", "duplicate"] }
//   PATCH /api/feedback/<id>/triage  { "priority": null }   // clear
router.patch('/:id/triage', requireAuth, async (req, res) => {
    try {
        const data = UpdateFeedbackTriageSchema.parse(req.body);

        const sets: string[] = [];
        const values: any[] = [];
        let i = 1;

        if (data.labels !== undefined) {
            sets.push(`labels = $${i++}`);
            values.push(data.labels);
        }
        if (data.priority !== undefined) {
            sets.push(`priority = $${i++}`);
            values.push(data.priority);
        }

        if (sets.length === 0) {
            res.status(400).json({ success: false, error: 'No triage fields provided' });
            return;
        }

        values.push(req.params.id);
        const result = await query<{ id: string; labels: string[]; priority: string | null }>(
            `UPDATE feedback SET ${sets.join(', ')} WHERE id = $${i} RETURNING id, labels, priority`,
            values,
        );

        if (result.rows.length === 0) {
            res.status(404).json({ success: false, error: 'Feedback not found' });
            return;
        }

        res.json({ success: true, data: result.rows[0] });
    } catch (error) {
        if (error instanceof z.ZodError) {
            res.status(400).json({ success: false, error: 'Validation failed', details: error.errors });
        } else {
            const msg = error instanceof Error ? error.message : String(error);
            res.status(500).json({ success: false, error: msg });
        }
    }
});

export default router;
