-- Invitation tokens: admin-initiated email invites for users who haven't signed up yet.
-- Token is a 64-char hex string generated by gen_random_bytes(32).
-- Row is consumed (accepted_at set) when the invitee completes registration.

CREATE TABLE IF NOT EXISTS invite_tokens (
  id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  email           TEXT        NOT NULL,
  token           TEXT        UNIQUE NOT NULL DEFAULT encode(gen_random_bytes(32), 'hex'),
  invited_by_user_id TEXT,
  role            TEXT        NOT NULL DEFAULT 'user' CHECK (role IN ('admin', 'user')),
  accepted_at     TIMESTAMPTZ,
  expires_at      TIMESTAMPTZ NOT NULL DEFAULT (NOW() + INTERVAL '7 days'),
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_invite_tokens_token ON invite_tokens(token);
CREATE INDEX IF NOT EXISTS idx_invite_tokens_email ON invite_tokens(email);
